# Generated by Django 6.0.7 on 2026-08-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_required',
            field=models.CharField(default='1 unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('produce', 'Produce'), ('dairy', 'Dairy & Eggs'), ('meat', 'Meat & Seafood'), ('pantry', 'Pantry Essentials'), ('beverage', 'Beverages')], default='pantry', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_shelf_life',
            field=models.IntegerField(default=7, help_text='Default shelf life in days'),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default=15, help_text='Prep time in minutes'),
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
    ]
